### ISSUE TITLE
this does no update the state of the list

### ISSUE THREAD

**Issue by shadow7789** [andynoir/vuetify-table-drag#14]
the code does not update the state of the list, so in other words even if on UI u can drag it around it does not update the state, and if u don't update the state what's the point?

![error](https://user-images.githubusercontent.com/39288008/132936499-95ae573e-7601-4a80-a9a8-bcc9b4dff049.gif)

**Comment by gaisinskii** [comment]
@shadow7789 First of all what's the point of creating an issue here? Secondly, it's already have been answered https://dev.to/andynoir/comment/1bioe
